### ISSUE TITLE
Gudetama shit command

### ISSUE THREAD

**Issue by sleepower** [WaifuShork/NamorokaBot#8]
![3310DA8B-01AB-4F63-A32D-FC9861E70D3E](https://user-images.githubusercontent.com/44559962/90296821-bf323280-dee0-11ea-9b2b-63b7d59cb8b6.jpeg)

I want a gudetama shits command, the horrific look of faces with bring me joy

**Comment by WaifuShork** [comment]
Added gudetama as an executable command
